name: Build

on:
  # Trigger this workflow on push to the included branches
  push:
    branches: [main]
  # Trigger this workflow on pull request against the included branches
  pull_request:
    branches: [main]
  # Allows running this workflow manually from the actions tab
  workflow_dispatch:
  
#Run the job below
jobs:  
  #Job 1: Build apk
  build:
    runs-on: ubuntu-latest
    
    steps:
      #Check out the code to the runner
      - name: Checkout the code
        uses: actions/checkout@v2
        
      #Cache Gradle
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      #Setup JDK on the runner
      - name: Use Java8
        uses: actions/setup-java@v1
        with:
            java-version: 11

      #Build debug apk
      - name: Build debug apk
        run: ./gradlew clean assembleDebug --stacktrace

      #Upload generated apk to artifacts
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk
