name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Create local.properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Use Java 17
        uses: actions/setup-java@v1
        with:
            java-version: 17

      - name: Build debug apk
        run: ./gradlew clean assembleDebug --stacktrace

      - name: List APK files
        run: find app/build/outputs/apk -type f -name "*.apk"

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/drovox-debug-*.apk
